# Generated by Django 5.0.2 on 2024-03-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('pickup_date', models.DateField()),
                ('return_date', models.DateField()),
                ('car_type', models.CharField(max_length=255)),
                ('car_id', models.IntegerField()),
            ],
        ),
    ]
