# Generated by Django 5.0.3 on 2024-03-16 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='car_type',
            new_name='car_model',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='car_id',
        ),
    ]
