# Generated by Django 4.2.11 on 2024-03-29 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0003_reservation_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Agreement Sent", "Agreement Sent"),
                    ("Agreement Signed", "Agreement Signed"),
                    ("Under Review", "Under Review"),
                    ("Accepted", "Accepted"),
                    ("pPayment Pending", "Payment Pending"),
                    ("Completed", "Completed"),
                    ("Cancelled", "Cancelled"),
                    ("Return Accepted", "Return Accepted"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
