# Generated by Django 4.2.11 on 2024-04-12 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0007_alter_reservation_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="discountAmount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
