# Generated by Django 4.2.11 on 2024-04-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0008_reservation_discountamount"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="car_seat_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="reservation",
            name="gps",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reservation",
            name="insurance",
            field=models.BooleanField(default=False),
        ),
    ]
