# Generated by Django 4.2.11 on 2024-04-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0009_reservation_car_seat_count_reservation_gps_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="points_used",
            field=models.IntegerField(
                default=0, help_text="Points used for the reservation"
            ),
        ),
    ]
