# Generated by Django 5.0.3 on 2024-03-15 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carform', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
