# Generated by Django 4.2.11 on 2024-03-25 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental_agreements", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="rentalagreement", name="agreement_file",),
        migrations.RemoveField(model_name="rentalagreement", name="rejection_reason",),
        migrations.AddField(
            model_name="rentalagreement",
            name="signed_agreement",
            field=models.FileField(
                blank=True, null=True, upload_to="signed_agreements/"
            ),
        ),
        migrations.AlterField(
            model_name="rentalagreement",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("under_review", "Under Review"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
