# Generated by Django 5.0.3 on 2024-03-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_remove_car_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(default='default_car_image.jpg', upload_to='car_images'),
        ),
    ]
