# Generated by Django 4.2.11 on 2024-03-25 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="bankaccount", name="account_balance",),
        migrations.RemoveField(model_name="transaction", name="created_at",),
        migrations.RemoveField(model_name="transaction", name="reservation",),
        migrations.AddField(
            model_name="bankaccount",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="credit_card_number",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="transaction",
            name="transaction_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[("payment", "Payment"), ("reimbursement", "Reimbursement")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(name="RentalAgreement",),
    ]
