# Generated by Django 4.2.11 on 2024-03-25 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_remove_bankaccount_account_balance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankaccount",
            name="credit_card_number",
            field=models.CharField(max_length=16),
        ),
    ]
