# Generated by Django 4.2.11 on 2024-04-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0003_alter_bankaccount_credit_card_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
